authKakao:
  handler: src/functions/auth/kakao-start/handler.main
  events:
    - http:
        path: auth/kakao
        method: get

authKakoCallback:
  handler: src/functions/auth/kakao-callback/handler.main
  events:
    - http:
        path: auth/kakao/callback
        method: get

chatListUserChat:
  handler: src/functions/chat/list-user-chats/handler.main
  events:
    - http:
        path: chat/list-user-chats
        method: get
