authKakao:
  handler: src/functions/auth/kakao-start/handler.main
  events:
    - http:
        path: auth/kakao
        method: get

authKakoCallback:
  handler: src/functions/auth/kakao-callback/handler.main
  events:
    - http:
        path: auth/kakao/callback
        method: get
#
